Repository anthony-gudiel/reactpedia, pull requests merged in 2023-11, with the labels that each got.

#28 Create vercel.yml
  .github/workflows/React-build-test.yml
  .github/workflows/Vercel-deployment.yml
Labels: website

#30 Updated README.md
  README.md
Labels: documentation

#37 Set up Vitest
  .github/workflows/React-build-test.yml
  README.md
  app/package-lock.json
  app/package.json
  app/test/App.test.jsx
Labels: documentation, CI/CD, test

#38 Embed video
  .github/workflows/React-build-test.yml
  app/.gitignore
  app/package-lock.json
  app/package.json
  app/src/api/youtube.jsx
  app/src/components/Search.jsx
  app/src/components/YouTubeEmbedVideo.jsx
  app/src/pages/content/content.css
  app/src/pages/content/content.jsx
  app/vite.config.js
Labels: API, YouTube

#45 Switch Between YouTube Videos
  app/package-lock.json
  app/package.json
  app/src/components/Search.css
  app/src/components/Search.jsx
  app/src/components/header.css
  app/src/pages/content/content.css
  app/src/pages/content/content.jsx
  app/src/pages/content/lesson-1-1.css
  app/src/pages/home/home.css
Labels: API, YouTube

#51 Created Second Lesson
  app/src/App.jsx
  app/src/components/header.css
  app/src/index.css
  app/src/pages/content/lesson-1-1.css
  app/src/pages/content/lesson-1-1.jsx
  app/src/pages/content/lesson-1-2-answers.jsx
  app/src/pages/content/lesson-1-2.jsx
  app/src/pages/content/lesson-1-3.jsx
  app/src/pages/home/home.css
  app/src/pages/home/home.jsx
Labels: content, CSS

#57 Fixed display for larger screens in lessons, video player, and home
  app/src/components/Search.css
  app/src/components/header.css
  app/src/pages/content/lesson-1-1.jsx
  app/src/pages/home/home.css
Labels: bug, content, CSS

#65 Changed Links in Header
  app/.env
  app/src/App.jsx
  app/src/api/openai.jsx
  app/src/components/header.css
  app/src/components/header.jsx
  app/src/pages/content/lesson-1-1.css
  app/src/pages/content/lesson-1-1.jsx
  app/src/pages/content/lesson-1-2.jsx
  app/src/pages/content/tutorials.css
  app/src/pages/content/tutorials.jsx
  app/src/pages/quizzes/quizzes.jsx
  app/src/pages/resources/content.jsx
  app/src/pages/resources/resources.jsx
Labels: CSS

#66 Added tests for the search feature
  app/src/pages/content/tutorials.jsx
  app/test/Search.test.jsx
Labels: YouTube, test

#75 73/open-ai-3
  .github/workflows/React-build-test.yml
  .gitignore
  app/.env
  app/src/api/openai.jsx
  app/src/pages/about/about.css
  app/src/pages/content/lesson-1-1.css
  app/src/pages/content/lesson-1-1.jsx
  app/src/pages/content/lesson-1-2.jsx
  app/src/pages/content/tutorials.jsx
  app/src/pages/quizzes/quizzes.jsx
  app/vite.config.js
Labels: API, CSS, OpenAI

#78 Fixed OpenAI key name
  app/index.html
  app/src/api/openai.jsx
  app/src/pages/content/tutorials.jsx
Labels: bug, API

#80 Added support for manual workflow triggers
  .github/workflows/React-build-test.yml
Labels: enhancement

#82 Fixed Vercel OpenAI key
  .github/workflows/Vercel-deployment.yml
  app/src/api/openai.jsx
Labels: bug

#84 Subscribe Feature
  app/src/pages/content/tutorials.jsx
  app/vite.config.js
Labels: API, YouTube

#87 Subscription button toggle
  app/src/App.jsx
  app/src/pages/content/tutorials.css
  app/src/pages/content/tutorials.jsx
  app/src/pages/tutorials/tutorials.css
  app/src/pages/tutorials/tutorials.jsx
  app/test/Search.test.jsx
Labels: enhancement, API, YouTube

#96 20/youtube playlist
  app/src/pages/tutorials/tutorials.css
  app/src/pages/tutorials/tutorials.jsx
Labels: enhancement, API, YouTube

#99 Reorganized Headers
  app/src/App.jsx
  app/src/api/openai.jsx
  app/src/components/header.css
  app/src/components/header.jsx
  app/src/pages/about/about.jsx
  app/src/pages/compiler/compiler.css
  app/src/pages/compiler/compiler.jsx
  app/src/pages/content/lesson-1-1.jsx
  app/src/pages/content/lesson-1-2.jsx
  app/src/pages/content/lesson-1-3.jsx
  app/src/pages/content/lesson-1-4.jsx
  app/src/pages/home/home.css
  app/src/pages/home/home.jsx
  app/src/pages/lessons/lesson-1-1.css
  app/src/pages/lessons/lesson-1-1.jsx
  app/src/pages/lessons/lesson-1-2-answers.jsx
  app/src/pages/lessons/lesson-1-2.jsx
  app/src/pages/lessons/lesson-1-3.jsx
  app/src/pages/lessons/lesson-1-4.jsx
  app/src/pages/quizzes/quizzes.jsx
  app/src/pages/videos/videos.css
  app/src/pages/videos/videos.jsx
  app/test/App.test.jsx
  app/test/Search.test.jsx
Labels: enhancement
